/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Control.Controladora;
import dominio.Archivo;
import dominio.SocketCliente;
import dominio.Usuario;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author richa
 */
public class Menu extends javax.swing.JFrame {
    
    Controladora control;
    Socket socket;
    String user, pass;
    
    
    /**
     * Creates new form Menu
     */
    public Menu(String username, String password) {
        initComponents();
        user = username;
        pass = password;
        control = new Controladora (this);
    }
    
    public Menu() {
        initComponents();
        control = new Controladora (this);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bcommit = new javax.swing.JButton();
        Bupdate = new javax.swing.JButton();
        Bcheckout = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        PanelVacio = new javax.swing.JPanel();
        PanelCommit = new javax.swing.JPanel();
        PanelUpdate = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUpdate = new javax.swing.JTable();
        buArchivoUpdate = new javax.swing.JButton();
        PanelCheckout = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCheckout = new javax.swing.JTable();
        buArchivoCheckout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bcommit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/checkmark.png"))); // NOI18N
        Bcommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcommitActionPerformed(evt);
            }
        });

        Bupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/61076.png"))); // NOI18N
        Bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BupdateActionPerformed(evt);
            }
        });

        Bcheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/61437-200.png"))); // NOI18N
        Bcheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcheckoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bcheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Bcommit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Bcommit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Bcheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout PanelVacioLayout = new javax.swing.GroupLayout(PanelVacio);
        PanelVacio.setLayout(PanelVacioLayout);
        PanelVacioLayout.setHorizontalGroup(
            PanelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        PanelVacioLayout.setVerticalGroup(
            PanelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        jLayeredPane1.add(PanelVacio, "card5");

        javax.swing.GroupLayout PanelCommitLayout = new javax.swing.GroupLayout(PanelCommit);
        PanelCommit.setLayout(PanelCommitLayout);
        PanelCommitLayout.setHorizontalGroup(
            PanelCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        PanelCommitLayout.setVerticalGroup(
            PanelCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        jLayeredPane1.add(PanelCommit, "card2");

        tablaUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaUpdate);

        buArchivoUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/download-icon-down-arrow-23.png"))); // NOI18N
        buArchivoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buArchivoUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelUpdateLayout = new javax.swing.GroupLayout(PanelUpdate);
        PanelUpdate.setLayout(PanelUpdateLayout);
        PanelUpdateLayout.setHorizontalGroup(
            PanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buArchivoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );
        PanelUpdateLayout.setVerticalGroup(
            PanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUpdateLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buArchivoUpdate)
                .addGap(21, 21, 21))
        );

        jLayeredPane1.add(PanelUpdate, "card3");

        tablaCheckout.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaCheckout);

        buArchivoCheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/download-icon-down-arrow-23.png"))); // NOI18N
        buArchivoCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buArchivoCheckoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCheckoutLayout = new javax.swing.GroupLayout(PanelCheckout);
        PanelCheckout.setLayout(PanelCheckoutLayout);
        PanelCheckoutLayout.setHorizontalGroup(
            PanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
            .addGroup(PanelCheckoutLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(buArchivoCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCheckoutLayout.setVerticalGroup(
            PanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCheckoutLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buArchivoCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane1.add(PanelCheckout, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BcommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcommitActionPerformed
        //control.activarPanel(PanelCommit, PanelUpdate, PanelCheckout, PanelVacio);
        try{
            socket = new Socket("192.168.0.100",8000);
        }catch (IOException ex){
            System.out.println("Error de conexión en el commit.");
        }
        JFileChooser filechooser=new JFileChooser();
        int returnVal = filechooser.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION)
            {
                File file = filechooser.getSelectedFile();
                DataInputStream input;
                BufferedInputStream bis;
                BufferedOutputStream bos;
                int in;
                byte[] byteArray;
                try
                {
                    bis = new BufferedInputStream(new FileInputStream(file));                  
                    bos = new BufferedOutputStream(socket.getOutputStream());
                    DataOutputStream dos = new DataOutputStream(socket.getOutputStream());
                    dos.writeUTF("002-"+user);
                    System.out.println("Commit enviado.");
                    dos.writeUTF(file.getName());
                    JOptionPane.showMessageDialog(this, "Envío satisfactorio.");
                    //Enviamos el fichero
                    byteArray = new byte[8192];
                    while ((in = bis.read(byteArray)) != -1){
                        bos.write(byteArray,0,in);
                    }
                    bis.close();
                    bos.close();
                }catch ( Exception e ) {
                    System.err.println("Error en commit. "+e);
                }
            } 
            else 
            {
                JOptionPane.showMessageDialog(this, "Opción cancelada.");
            }
    }//GEN-LAST:event_BcommitActionPerformed

    private void BupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BupdateActionPerformed
        control.activarPanel(PanelUpdate, PanelCommit, PanelCheckout, PanelVacio);
        tablaUpdate.setModel(new javax.swing.table.DefaultTableModel(new Object [][] {}, new String [] {"Nombre del Archivo", "Fecha de subida"}));
        JOptionPane.showMessageDialog(this, "Buscando archivos...");
        Archivo archivo = null;
        ArrayList<Archivo> listaArchivos = null;
        try{
            socket = new Socket("192.168.0.100",8000);
        }catch (IOException ex){
            System.out.println("Error de conexion en el update.");
        }
        try{
            DataOutputStream dos;
            dos = new DataOutputStream(socket.getOutputStream());
            dos.writeUTF("003-"+user);
            System.out.println("Update enviado.");
            ObjectInputStream ois;
            ois  = new ObjectInputStream(socket.getInputStream());
            listaArchivos = (ArrayList) ois.readObject();
            System.out.println("Recibiendo archivos del update.");
            ois.close();
            dos.close();      
        }catch (IOException ex){
            System.out.println("Error de conexión en el update.");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        control.llenarTabla(listaArchivos, tablaUpdate);
        JOptionPane.showMessageDialog(this, "Operación exitosa");
    }//GEN-LAST:event_BupdateActionPerformed

    private void BcheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcheckoutActionPerformed
        control.activarPanel(PanelCheckout, PanelUpdate, PanelCommit, PanelVacio);
        tablaCheckout.setModel(new javax.swing.table.DefaultTableModel(new Object [][] {}, new String [] {"Nombre del Archivo", "Fecha de subida"}));
        JOptionPane.showMessageDialog(this, "Buscando archivos...");
        Archivo archivo = null;
        ArrayList<Archivo> listaArchivos = null;
        try{
            socket = new Socket("192.168.0.100",8000);
        }catch (IOException ex){
            System.out.println("Error de conexion en el checkout.");
        }
        try{
            DataOutputStream dos;
            dos = new DataOutputStream(socket.getOutputStream());
            dos.writeUTF("004-"+user);
            System.out.println("Checkout enviado");
            ObjectInputStream ois;
            ois  = new ObjectInputStream(socket.getInputStream());
            listaArchivos = (ArrayList) ois.readObject();
            System.out.println("Operación exitosa");
            ois.close();
            dos.close();
      
        }catch (IOException ex){
            System.out.println("Error de conexión en el checkout");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        control.llenarTabla(listaArchivos, tablaCheckout);
        JOptionPane.showMessageDialog(this, "Operación exitosa");
    }//GEN-LAST:event_BcheckoutActionPerformed

    private void buArchivoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buArchivoUpdateActionPerformed
        int row = tablaUpdate.getSelectedRow();
        String name = tablaUpdate.getValueAt(row, 0).toString();
        String date = tablaUpdate.getValueAt(row, 1).toString();
        try{
            socket = new Socket("192.168.0.100",8000);
        }catch (IOException ex){
            System.out.println("Error de conexión en el update.");
        }
        try{
            DataOutputStream dos;
            dos = new DataOutputStream(socket.getOutputStream());
            dos.writeUTF("005-"+user+"-"+name+"-"+date);
            System.out.println("Datos enviados");
            JOptionPane.showMessageDialog(this, "Localizando archivo");
            BufferedInputStream bis;
            BufferedOutputStream bos;
            byte[] receivedData;
            int in;
            String file;
             //Buffer de 1024 bytes
            receivedData = new byte[1024];
            bis = new BufferedInputStream(socket.getInputStream());
            DataInputStream dis = new DataInputStream(socket.getInputStream());
            //Recibimos el nombre del fichero
            file = dis.readUTF();
            file = file.substring(file.indexOf('\\')+1,file.length());
            //Para guardar fichero recibido
            bos = new BufferedOutputStream(new FileOutputStream(file));
            while ((in = bis.read(receivedData)) != -1){
                bos.write(receivedData,0,in);
            }
            bos.close();
            dis.close();
            int prueba = control.crearArchivo(user, file, 0);
            if(prueba==1){
                JOptionPane.showMessageDialog(this, "Archivo descargado");
            }
            if(prueba==0){
                JOptionPane.showMessageDialog(this, "Archivo no encontrado");
            }
            dos.close();
        }catch (IOException ex){
            System.out.println("Error de conexión en el update");
        }
    }//GEN-LAST:event_buArchivoUpdateActionPerformed

    private void buArchivoCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buArchivoCheckoutActionPerformed
        int row = tablaCheckout.getSelectedRow();
        String name = tablaCheckout.getValueAt(row, 0).toString();
        String date = tablaCheckout.getValueAt(row, 1).toString();
        try{
            socket = new Socket("192.168.0.100",8000);
        }catch (IOException ex){
            System.out.println("Error de conexion en el checkout");
        }
        try{
            System.out.println("Conexión iniciada");
            DataOutputStream dos;
            dos = new DataOutputStream(socket.getOutputStream());
            dos.writeUTF("006-"+user+"-"+name+"-"+date);
            System.out.println("Archivos enviados");
            JOptionPane.showMessageDialog(this, "Localizando archivo");
            BufferedInputStream bis;
            BufferedOutputStream bos;
            byte[] receivedData;
            int in;
            String file;
             //Buffer de 1024 bytes
            receivedData = new byte[1024];
            bis = new BufferedInputStream(socket.getInputStream());
            DataInputStream dis = new DataInputStream(socket.getInputStream());
            //Recibimos el nombre del fichero
            file = dis.readUTF();
            file = file.substring(file.indexOf('\\')+1,file.length());
            //Para guardar fichero recibido
            bos = new BufferedOutputStream(new FileOutputStream(file));
            while ((in = bis.read(receivedData)) != -1){
                bos.write(receivedData,0,in);
            }
            bos.close();
            dis.close();
            int prueba = control.crearArchivo(user, file, 0);
            if(prueba==1){
                JOptionPane.showMessageDialog(this, "Archivo descargado");
            }
            if(prueba==0){
                JOptionPane.showMessageDialog(this, "Archivo no encontrado");
            }
            dos.close();
        }catch (IOException ex){
            System.out.println("Error de conexion en el checkout.");
        }
    }//GEN-LAST:event_buArchivoCheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcheckout;
    private javax.swing.JButton Bcommit;
    private javax.swing.JButton Bupdate;
    private javax.swing.JPanel PanelCheckout;
    private javax.swing.JPanel PanelCommit;
    private javax.swing.JPanel PanelUpdate;
    private javax.swing.JPanel PanelVacio;
    private javax.swing.JButton buArchivoCheckout;
    private javax.swing.JButton buArchivoUpdate;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaCheckout;
    private javax.swing.JTable tablaUpdate;
    // End of variables declaration//GEN-END:variables
}
